version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    # command: "pytest -s -v --maxfail=1 --disable-warnings -q "
    # command: "python3 tests/test_pipeline.py"
