#

version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app # Mounts the project root to /app in the container
    working_dir: /app
    command: "pytest -v --maxfail=1 --disable-warnings -q"
